.TH "TOOL-BUILD-WATCH" "1" "September 28, 2026" "tool 2.3.1" "User Commands"
.SH "NAME"
tool\-build\-watch, tool\-build\-w \- Watch and rebuild on change
.SH "SYNOPSIS"
\fBtool build watch|w\fR [\fIoptions\fR]
.SH "DESCRIPTION"
Watch and rebuild on change
.SH "OPTIONS"
.TP
\fB\-i, \-\-interval <ms>\fR
poll interval in milliseconds (default: "500")
.TP
\fB\-h, \-\-help\fR
display help for command
.SH "SEE ALSO"
.BR tool\-build (1)
