.TH "TOOL-LINT" "1" "September 28, 2026" "tool 2.3.1" "User Commands"
.SH "NAME"
tool\-lint \- \&'Lint the project.' Uses a backslash path separator
like C:\eUsers on Windows.
.SH "SYNOPSIS"
\fBtool lint\fR [\fIoptions\fR]
.SH "DESCRIPTION"
\&'Lint the project.' Uses a backslash path separator like C:\eUsers
on Windows.
.SH "OPTIONS"
.TP
\fB\-\-fix\fR
automatically fix problems
.TP
\fB\-h, \-\-help\fR
display help for command
.SH "SEE ALSO"
.BR tool (1),
.BR tool\-build (1),
.BR tool\-deploy (1)
