.TH "TOOL-DEPLOY" "1" "September 28, 2026" "tool 2.3.1" "User Commands"
.SH "NAME"
tool\-deploy \- deploy the project (implemented as a separate
executable)
.SH "SYNOPSIS"
\fBtool deploy\fR [\fIoptions\fR] [target]
.SH "DESCRIPTION"
deploy the project (implemented as a separate executable)
.SH "OPTIONS"
.TP
\fB\-h, \-\-help\fR
display help for command
.SH "SEE ALSO"
.BR tool (1),
.BR tool\-build (1),
.BR tool\-lint (1)
